[package]
description = "A toolbox of basic data structures and algorithms"
edition = "2021"
homepage = "https://github.com/DennisOSRM/toolbox-rs"
license = "MIT"
name = "toolbox-rs"
readme = "README.md"
repository = "https://github.com/DennisOSRM/toolbox-rs"
version = "0.1.3"

[[example]]
name = "instantiate"

[[bin]]
name = "chipper"
path = "src/chipper/bin/main.rs"

[dependencies]
bitvec = "1.0.0"
clap = { version = "3.1.18", features = ["derive"] }
criterion = "0.3.5"
env_logger = "0.9.0"
itertools = "0.10.3"
log = "0.4.16"
num = "0.4.0"
rand = "0.8.4"
rayon = "1.5.2"

[profile.release]
debug = true

[[bench]]
name = "bench_main"
harness = false
