[package]
name = "toolbox"
version = "0.1.0"
edition = "2021"

[[example]]
name = "instantiate"

[[example]]
name = "web_server"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "0.22.3"
itertools = "0.10.3"
num = "0.4.0"
rand = "0.8.4"

[profile.release]
debug = true
