[package]
description = "A toolbox of basic data structures and algorithms"
edition = "2021"
homepage = "https://github.com/DennisOSRM/toolbox-rs"
license = "MIT"
name = "toolbox-rs"
readme = "README.md"
repository = "https://github.com/DennisOSRM/toolbox-rs"
version = "0.1.6"

[[example]]
name = "instantiate"

[[bin]]
name = "chipper"
path = "src/chipper/bin/main.rs"

[[bin]]
name = "scaffold"
path = "src/scaffold/bin/main.rs"

[[bin]]
name = "graph_plier"
path = "src/graph_plier/bin/main.rs"

[dependencies]
bincode = "1.3.3"
bitvec = "1.0.0"
clap = { version = "4.1.8", features = ["derive"] }
criterion = "0.4.0"
env_logger = "0.10.0"
fxhash = "0.2.1"
geojson = "0.24.0"
indicatif = "0.17.3"
itertools = "0.10.4"
log = "0.4.16"
num = "0.4.0"
rand = "0.8.4"
rayon = "1.7.0"
serde = { version = "1.0.159", features = ["derive"] }
xxhash-rust = {version = "0.8.5", features = ["xxh3"] }

[profile.release]
debug = true
lto = true

[[bench]]
name = "bench_main"
harness = false
