[package]
description = "A toolbox of basic data structures and algorithms"
edition = "2021"
homepage = "https://github.com/DennisOSRM/toolbox"
license = "MIT"
name = "toolbox-rs"
readme = "README.md"
repository = "https://github.com/DennisOSRM/toolbox"
version = "0.1.2"

[[example]]
name = "instantiate"

[dependencies]
bitvec = "0.22.3"
criterion = "0.3.5"
itertools = "0.10.3"
num = "0.4.0"
rand = "0.8.4"

[profile.release]
debug = true

[[bench]]
name = "distance"
harness = false
