[package]
description = "A toolbox of basic data structures and algorithms"
edition = "2021"
homepage = "https://github.com/DennisOSRM/toolbox-rs"
license = "MIT"
name = "toolbox-rs"
readme = "README.md"
repository = "https://github.com/DennisOSRM/toolbox-rs"
version = "0.1.6"

[[example]]
name = "instantiate"

[[bin]]
name = "chipper"
path = "src/chipper/bin/main.rs"

[[bin]]
name = "scaffold"
path = "src/scaffold/bin/main.rs"

[[bin]]
name = "graph_plier"
path = "src/graph_plier/bin/main.rs"

[dependencies]
bincode = "1.3.3"
bitvec = "1.0.1"
clap = { version = "4.5.20", features = ["derive"] }
env_logger = "0.11.5"
fxhash = "0.2.1"
geojson = "0.24.1"
indicatif = "0.17.8"
itertools = "0.13.0"
log = "0.4.22"
num = "0.4.3"
rand = "0.8.5"
rayon = "1.10.0"
serde = { version = "1.0.210", features = ["derive"] }
xxhash-rust = {version = "0.8.12", features = ["xxh3"] }

[dev-dependencies]
criterion = "0.5.1"

[profile.release]
debug = true
lto = true

[[bench]]
name = "bench_main"
harness = false
