name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        arch: [X64, ARM64]

    runs-on: [self-hosted, linux]

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --all-targets
    - name: Run tests
      run: cargo test
